### PR TITLE
Tidy up the code for readability and to remove warnings

### PR DESCRIPTION
**Pull request by codders**

### CODE REVIEW

**Comment by alexhumphreys** [comment]
Maybe [this article](https://eev.ee/blog/2013/03/03/the-controller-pattern-is-awful-and-other-oo-heresy/#the-controller-antipattern) just got to me, but I kind of prefer the pre refactor one...

**Comment by codders** [comment]
I take your point, and I agree it's less than pretty, but the entire Sinatra API basically assumes that your Sinatra programs are classes that are bunches of functions. This is the tidiest way to create my check functions without creating a full-blown DSL, or requiring me to add the test functions manually to an array of functions.

Do you have an alternative suggestion that doesn't create a "class variable access from toplevel" warning? (that was the issue with the pre-refactor version)

**Comment by alexhumphreys** [comment]
Hmm good points. There's maybe some jazz you could do with modules and metaprogramming `test_*` methods, but 1/ I don't know if that'll work, and 2/ it probably counts as a full-blown DSL. I also don't know Sinatra's API, so yeah, no suggestions.

It'd probably be more than its worth to change it, and could involve bending Sinatra, so probably best to go with what is. Feel free to merge.

**Comment by alexhumphreys** [comment]
Review Score: 7/11

**Pull request merged**
